language: elixir
elixir:
  - 1.3.4
  - 1.4.0
  - 1.5.1
otp_release:
  - 18.3
  - 19.2
  - 20.0
script:
  - "MIX_ENV=test mix do deps.get, test && mix credo && mix coveralls.travis"
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
